import { Activity } from './Activity';

export const MOCK_ACTIVITIES = [
  new Activity({
    _id: '1',
    name: 'Actividad de prueba',
    sport_id: 123,
    category: 'Categoría de prueba',
    description: 'Esta es una descripción de prueba',
    multimedia_links: ['link1', 'link2'],
    rating: 4.5,
    tags: ['tag1', 'tag2'],
    user_id: 456,
  }),
  new Activity({
    _id: '2',
    name: 'Actividad de prueba',
    sport_id: 123,
    category: 'Categoría de prueba',
    description: 'Esta es una descripción de prueba',
    multimedia_links: ['link1', 'link2'],
    rating: 4.5,
    tags: ['tag1', 'tag2'],
    user_id: 456,
  }),
  new Activity({
    _id: '3',
    name: 'Actividad de prueba',
    sport_id: 123,
    category: 'Categoría de prueba',
    description: 'Esta es una descripción de prueba',
    multimedia_links: ['link1', 'link2'],
    rating: 4.5,
    tags: ['tag1', 'tag2'],
    user_id: 456,
  }),
  new Activity({
    _id: '4',
    name: 'Actividad de prueba',
    sport_id: 123,
    category: 'Categoría de prueba',
    description: 'Esta es una descripción de prueba',
    multimedia_links: ['link1', 'link2'],
    rating: 4.5,
    tags: ['tag1', 'tag2'],
    user_id: 456,
  }),
  new Activity({
    _id: '5',
    name: 'Actividad de prueba',
    sport_id: 123,
    category: 'Categoría de prueba',
    description: 'Esta es una descripción de prueba',
    multimedia_links: ['link1', 'link2'],
    rating: 4.5,
    tags: ['tag1', 'tag2'],
    user_id: 456,
  }),
  new Activity({
    _id: '6',
    name: 'Actividad de prueba',
    sport_id: 123,
    category: 'Categoría de prueba',
    description: 'Esta es una descripción de prueba',
    multimedia_links: ['link1', 'link2'],
    rating: 4.5,
    tags: ['tag1', 'tag2'],
    user_id: 456,
  }),
  new Activity({
    _id: '7',
    name: 'Actividad de prueba',
    sport_id: 123,
    category: 'Categoría de prueba',
    description: 'Esta es una descripción de prueba',
    multimedia_links: ['link1', 'link2'],
    rating: 4.5,
    tags: ['tag1', 'tag2'],
    user_id: 456,
  }),
];